apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-1-4-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kube-1-4-app
  template:
    metadata:
      labels:
        app: kube-1-4-app
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80

        - name: multitool
          image: wbitt/network-multitool:openshift
          env:
            - name: HTTP_PORT
              value: "8080"
          ports:
            - containerPort: 8080

