apiVersion: v1
kind: Service
metadata:
  name: kube-1-4-app-svc
spec:
  selector:
    app: kube-1-4-app
  type: ClusterIP
  ports:
  - name: nginx
    port: 9001
    targetPort: 80
  - name: multitool
    port: 9002
    targetPort: 8080