---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: kube-1-5-02-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /shared
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kube-1-5-02-pvc
spec:
  volumeName: kube-1-5-02-pv
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-1-5-02-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kube-1-5-02-app
  template:
    metadata:
      labels:
        app: kube-1-5-02-app
    spec:
      containers:
      - name: busybox
        image: busybox
        command: ["/bin/sh", "-c"] 
        args: ["echo $(date) > shared/data.txt; sleep 3600"] # КЛЮЧЕВОЕ: Команда записи данных в файл в директории из секции volumeMounts контейнера 
        volumeMounts:
        - name: shared-data
          mountPath: /shared
      - name: multitool
        image: busybox
        command: ["/bin/sh", "-c"]
        args: ["tail -f shared/data.txt"] # КЛЮЧЕВОЕ: Команда для чтения данных из файла, расположенного в директории, указанной в volumeMounts контейнера
        volumeMounts:
        - name: shared-data
          mountPath: /shared
      volumes:
      - name: shared-data
        persistentVolumeClaim:
          claimName: kube-1-5-02-pvc